apiVersion: v1
kind: Service
metadata:
  name: {{ include "phaeton.fullname" . }}-headless
  labels:
    {{- include "phaeton.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: epmd
      port: 4369
      targetPort: 4369
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
