{{- if not .Values.secret.existingSecret }}
{{- if not .Values.secret.secretKeyBase }}
{{- fail "Either secret.secretKeyBase or secret.existingSecret must be set." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phaeton.fullname" . }}
  labels:
    {{- include "phaeton.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key-base: {{ .Values.secret.secretKeyBase | quote }}
{{- end }}
